### ISSUE TITLE
Unable to look up a book

### ISSUE THREAD

**Issue by gooseleggs** [estebanthi/ObsidianTemplateVaultV2#2]
When trying out the template, I get a path not found when trying to look up a book.

Turns out the folder 14 References > Books > Inbox is missing.

You might want to update the code base to resolve this.

**Comment by estebanthi** [comment]
This directory is supposed to exist, however I can't commit empty directories with git. Will try to solve this by creating a dummy file in "Inbox" to commit this directory.
